name = "MyPkg31"
uuid = "a743e678-0a63-436a-b2cb-f3971b82879a"
authors = ["Shuhei Ohno"]
version = "0.0.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "1.11"
